name: Save and View Name

# Trigger the workflow manually
on:
  workflow_dispatch:

jobs:
  save-name:
    runs-on: ubuntu-latest
    outputs:
      artifact-path: ${{ steps.save-artifact.outputs.file-path }}
    steps:
      - name: Set up a name variable
        run: echo "MY_NAME=Your Name" >> $GITHUB_ENV
        
      - name: Echo name into a file
        run: echo ${{ env.MY_NAME }} > name.txt

      - name: Save the file as an artifact
        id: save-artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-name-file
          path: name.txt
          if-no-files-found: error

  view-name:
    needs: save-name
    runs-on: ubuntu-latest
    steps:
      - name: Download the artifact
        uses: actions/download-artifact@v3
        with:
          name: my-name-file

      - name: Display the contents of the file
        run: cat name.txt
